# Generated by Django 5.2.10 on 2026-01-20 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=100, verbose_name='菜名')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], default=3, verbose_name='难度')),
                ('duration', models.PositiveIntegerField(default=30, verbose_name='耗时(分钟)')),
                ('cover_url', models.URLField(blank=True, null=True, verbose_name='封面图')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='来源链接')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐')], default='lunch', max_length=20, verbose_name='餐段')),
                ('steps', models.JSONField(default=list, verbose_name='烹饪步骤')),
            ],
            options={
                'verbose_name': '食谱',
                'verbose_name_plural': '食谱',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('amount', models.CharField(default='适量', max_length=30, verbose_name='用量')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='ingredients.ingredient', verbose_name='食材')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='食谱')),
            ],
            options={
                'verbose_name': '食谱食材',
                'verbose_name_plural': '食谱食材',
            },
        ),
    ]
