# Generated by Django 5.2.10 on 2026-01-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_calories_and_more'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='每份可供几人食'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tips',
            field=models.TextField(blank=True, verbose_name='附加提示'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tools',
            field=models.JSONField(blank=True, default=list, help_text="工具列表数组，如：['锅', '铲子', '碗']", verbose_name='所需工具'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='steps',
            field=models.JSONField(default=list, help_text="格式：[{'step': 1, 'description': '...'}, ...]", verbose_name='烹饪步骤'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['meal_type'], name='recipe_meal_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['difficulty'], name='recipe_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_at'], name='recipe_created_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['recipe'], name='rec_ing_recipe_idx'),
        ),
        migrations.AddIndex(
            model_name='recipeingredient',
            index=models.Index(fields=['ingredient'], name='rec_ing_ing_idx'),
        ),
    ]
