# Generated by Django 5.2.10 on 2026-01-21 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_servings_recipe_tips_recipe_tools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('dessert', '甜点'), ('drink', '饮品')], default='lunch', max_length=20, verbose_name='餐段'),
        ),
    ]
