# Generated by Django 5.2.10 on 2026-01-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_dessert_drink_meal_types'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipe_meal_idx',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='recipe',
            name='meal_types',
            field=models.JSONField(default=list, help_text='可选值: breakfast, lunch, dinner, dessert, drink', verbose_name='适用餐段'),
        ),
    ]
