# Generated by Django 5.2.10 on 2026-01-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_change_meal_type_to_meal_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(blank=True, choices=[('aquatic', '水产'), ('breakfast', '早餐'), ('condiment', '调味品'), ('dessert', '甜点'), ('drink', '饮品'), ('meat_dish', '肉菜'), ('semi-finished', '半成品'), ('soup', '汤类'), ('staple', '主食'), ('vegetable_dish', '素菜')], help_text='菜品分类：aquatic/breakfast/condiment/dessert/drink/meat_dish/semi-finished/soup/staple/vegetable_dish', max_length=20, null=True, verbose_name='菜品类型'),
        ),
    ]
