# Generated by Django 5.2.10 on 2026-01-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cooked_recipes',
            field=models.JSONField(blank=True, default=dict, help_text="格式：{recipe_id: count}，如 {'1': 3, '25': 1}", verbose_name='已制作食谱'),
        ),
        migrations.AddField(
            model_name='user',
            name='disliked_ingredients',
            field=models.JSONField(blank=True, default=list, help_text='食材 ID 列表', verbose_name='不喜欢的食材'),
        ),
        migrations.AddField(
            model_name='user',
            name='disliked_recipes',
            field=models.JSONField(blank=True, default=list, help_text='食谱 ID 列表', verbose_name='不喜欢的食谱'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_recipes',
            field=models.JSONField(blank=True, default=list, help_text='食谱 ID 列表', verbose_name='收藏的食谱'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_ingredients',
            field=models.JSONField(blank=True, default=list, help_text='食材 ID 列表', verbose_name='喜欢的食材'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict, verbose_name='其他偏好设置'),
        ),
    ]
