# Generated by Django 5.2.10 on 2026-01-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名称')),
                ('category', models.CharField(choices=[('meat', '肉类'), ('vegetable', '蔬菜'), ('seafood', '海鲜'), ('egg_dairy', '蛋奶'), ('grain', '谷物'), ('seasoning', '调料'), ('other', '其他')], default='other', max_length=30, verbose_name='分类')),
                ('calories', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='热量(kcal/100g)')),
                ('protein', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='蛋白质(g/100g)')),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='脂肪(g/100g)')),
                ('carbs', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='碳水(g/100g)')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'ordering': ['category', 'name'],
            },
        ),
    ]
