# Generated by Django 5.2.10 on 2026-01-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='后续通过 DeepSeek API 自动填充', max_digits=7, null=True, verbose_name='热量(kcal/100g)'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['category'], name='ing_category_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['name'], name='ing_name_idx'),
        ),
    ]
